version: 2.1
orbs:
  docker: circleci/docker@0.5.13

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master
        - staging

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: pennlabs/pennlabs.org
    docker:
      - image: circleci/buildpack-deps:buster
jobs:
  test:
    working_directory: ~/pennlabs
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
  deploy:
    working_directory: ~/pennlabs
    docker:
      - image: pennlabs/labs-helm
    steps:
      - checkout
      - run:
          name: Deploy to k8s
          command: /deploy.sh
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - docker/publish:
          image: $IMAGE_NAME
          tag: $CIRCLE_SHA1
          context: docker-publish
          <<: *branch-filters
      - deploy:
          requires:
            - build-and-publish
          context: k8s-deploy
          <<: *branch-filters

