deploy_version: 0.1.8
image_tag: latest

applications:
  - name: react
    image: pennlabs/website
    secret: website
    port: 3000
    ingress:
      hosts:
        - host: pennlabs.org
          paths: ["/"]
